id;project;connector_type;t;delta_t;url;redirect_url;response_size;response_code;success;error
0;dji_data_collection;requests;1566890870.3969505;-0.016003131866455078;https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=^DJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX;;0;;False;HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=%5EDJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E17796F7F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
1;dji_data_collection;requests;1566890870.9244347;0.0;https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=^DJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX;;0;;False;HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=%5EDJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E17796F860>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
2;dji_data_collection;requests;1566890871.4262872;0.0;https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=^DJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX;;0;;False;HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=%5EDJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E17796F908>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
3;dji_data_collection;requests;1566890871.9284708;0.0;https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=^DJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX;;0;;False;HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=%5EDJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E17796FFD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
4;dji_data_collection;requests;1566890872.4357767;-0.004004478454589844;https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=^DJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX;;0;;False;HTTPSConnectionPool(host='www.alphavantage.co', port=443): Max retries exceeded with url: /query?function=TIME_SERIES_DAILY_ADJUSTED&symbol=%5EDJI&outputsize=full&apikey=Z6OIONR9OK9RAHMX (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001E17796FF28>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))